profile=gpu-hq
gpu-api=vulkan

autofit=50%
keep-open=yes
save-position-on-quit=yes
force-seekable=yes

cursor-autohide=100

alang=ja_,esp,spa,en,eng
slang=es,esp,spa,en,eng

volume=50
volume-max=100

demuxer-mkv-subtitle-preroll=yes
sub-ass-vsfilter-blur-compat=yes
sub-fix-timing=yes
sub-auto=fuzzy
sub-gauss=1.0
sub-gray=yes

sub-font=Andika New Basic Bold
sub-font-size=52
sub-blur=0.2
sub-border-color=0.0/0.0/0.0/1.0
sub-border-size=3.0
sub-color=1.0/1.0/1.0/1.0
sub-margin-x=100
sub-margin-y=50
sub-shadow-color=0.0/0.0/0.0/0.25
sub-shadow-offset=0

#Output format of screenshots
screenshot-format=png

#Same output bitdepth as the video
#Set it "no" if you want to save disc space
screenshot-high-bit-depth=yes

#Compression of the PNG picture (1-9)
#Higher value means better compression, but takes more time
screenshot-png-compression=1

#Quality of JPG pictures (0-100)
#Higher value means better quality
screenshot-jpeg-quality=100
#Output directory
screenshot-directory="C:\Pictures"

#Name format you want to save the pictures
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"

dither-depth=auto
dither=error-diffusion
error-diffusion=jarvis-judice-ninke

deband=yes
deband-iteration=8

deband-threshold=48
deband-range=16
deband-grain=48

glsl-shader="C:\Users\Coke\Desktop\mpv\shaders\nnedi3-nns32-win8x4.hook"
scale=ewa_lanczos
fbo-format=rgba16hf
no-scaler-resizes-only

glsl-shader="C:\Users\Coke\Desktop\mpv\shaders\SSimDownscaler.glsl"
dscale=gaussian
fbo-format=rgba16hf

glsl-shader="C:\Users\Coke\Desktop\mpv\shaders\KrigBilateral.glsl"
cscale=mitchell
fbo-format=rgba16hf

scale-antiring=0.7
dscale-antiring=0.7
cscale-antiring=0.7

#Subtitle blending in scenechanges (smoother effect)
#Important: Doesn't work with HDR content, set it "no" for HDR content!
blend-subtitles=yes

#Set the fps as the max. of your monitor Hz (only useful and needed with "interpolation=yes)
video-sync=display-resample

#Activate interpolation
interpolation=yes

tscale=box
tscale-window=sphinx
tscale-radius=1.0 #lower (e.g. 0.95) = sharper; higher (e.g. 1.05) = smoother 
tscale-clamp=0.0

deinterlace=auto

